### ISSUE TITLE
[Question] Does the adding the mod part disable achievements?

### ISSUE THREAD

**Issue by oof2win2** [DrSkunk/factorio-discord-death-counter#1]
Hi, I like this idea a lot. Does adding the 'mod' however disable achievements? I don't see anything being added to the mods folder, so I think it should allow achievements, I just want to ask to make sure.

**Comment by DrSkunk** [comment]
I don't believe it disables achievements because its a savefile mod and not a client mod. I'll doublecheck to be sure.

Edit: So, according to [this Reddit comment](https://www.reddit.com/r/factorio/comments/6cry7e/method_to_check_if_steam_achievements_are_still/), when viewing the achievements tab it should show the unatainable achievements in red. I modified the `control.lua` of a savefile and loaded it up in singleplayer and it shows all achievements as atainable.

**Comment by oof2win2** [comment]
Thanks for the info! Will probably implement!
